# Generated by Django 3.1 on 2020-08-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200810_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50)),
                ('intent', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('payer_email_address', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=50)),
                ('payer_country_code', models.CharField(max_length=20)),
                ('payer_first_name', models.CharField(max_length=100)),
                ('payer_last_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100)),
                ('final_capture', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('seller_protection_status', models.CharField(max_length=100)),
                ('dispute_categories', models.TextField()),
                ('links', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('payee_email_address', models.EmailField(max_length=254)),
                ('merchant_id', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=20)),
                ('shipping_to_name', models.CharField(max_length=100)),
                ('shipping_to_address', models.CharField(max_length=255)),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.payment')),
                ('payments_capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.paymentcapture')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('rel', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.payment')),
            ],
        ),
    ]
